apiVersion: v1
kind: Pod
metadata:
  name: email-notifier-operator
  namespace: email-notifier-operator
spec:
  containers:
  - name: email-notifier-operator
    image: shabbirsaifee/email-notifier-operator:1.0.0
    imagePullPolicy: Always
  serviceAccountName: email-notifier
